let movies = [
  {
    id: 1,
    title: "Dune: Part Two",
    titleVI: "Dune: Hành Tinh Cát - Phần 2",
    genres: "Khoa học viễn tưởng",
    duration: 166,
    releaseDate: "01/03/2024",
    status: 1,
    posterUrl: "../image/dune-part-two-poster.webp",
    description:
      "Tiếp nối phần trước, Paul Atreides hợp nhất với Fremen để trả thù gia tộc Harkonnen và đối mặt với số phận của vũ trụ.",
    ticketPrice: 95000,
  },
  {
    id: 2,
    title: "Kung Fu Panda 4",
    titleVI: "Kung Fu Panda 4",
    genres: "Hài",
    duration: 94,
    releaseDate: "08/03/2024",
    status: 0,
    posterUrl: "../image/kung-fu-panda-4-poster.webp",
    description:
      "Po tiếp tục hành trình trở thành Chiến binh Rồng, đối mặt với kẻ thù mới và tìm người kế nhiệm.",
    ticketPrice: 80000,
  },
  {
    id: 3,
    title: "Godzilla x Kong: The New Empire",
    titleVI: "Godzilla x Kong: Đế Chế Mới",
    genres: "Khoa học viễn tưởng",
    duration: 115,
    releaseDate: "29/03/2024",
    status: 2,
    posterUrl: "../image/godzilla-x-kong-poster.jpg",
    description:
      "Godzilla và Kong hợp sức chống lại mối đe dọa mới từ lòng đất.",
    ticketPrice: 80000,
  },
  {
    id: 4,
    title: "Mai",
    titleVI: "Mai",
    genres: "Tình cảm",
    duration: 131,
    releaseDate: "10/02/2024",
    status: 0,
    posterUrl: "../image/mai-poster.jpg",
    description:
      "Câu chuyện về một người phụ nữ mạnh mẽ đối mặt với những biến cố trong cuộc sống.",
    ticketPrice: 80000,
  },
  {
    id: 5,
    title: "Exhuma",
    titleVI: "Exhuma: Quật Mộ Trùng Ma",
    genres: "Giật gân",
    duration: 134,
    releaseDate: "15/03/2024",
    status: 2,
    posterUrl: "../image/exhuma-poster.jpg",
    description:
      "Một nhóm chuyên gia phong thủy khai quật mộ cổ và đối mặt với lời nguyền đáng sợ.",
    ticketPrice: 80000,
  },
  {
    id: 6,
    title: "Detective Conan: The Million-Dollar Pentagram",
    titleVI: "Thám tử lừng danh Conan: Ngôi sao 5 cánh 1 triệu đô",
    genres: "Hoạt hình",
    duration: 110,
    releaseDate: "12/04/2024",
    status: 2,
    posterUrl: "../image/conan-movie-27.webp",
    description:
      "Conan và nhóm bạn điều tra vụ án liên quan đến ngôi sao 5 cánh trị giá 1 triệu đô.",
    ticketPrice: 85000,
  },
  {
    id: 7,
    title: "Doraemon: New Nobita and the Castle of the Undersea Devil",
    titleVI: "Doraemon: Nobita và lâu đài dưới đáy biển",
    genres: "Hoạt hình",
    duration: 100,
    releaseDate: "20/04/2024",
    status: 2,
    posterUrl: "../image/doraemon-movie-45.webp",
    description:
      "Nobita và Doraemon khám phá lâu đài bí ẩn dưới đáy biển cùng những bí mật bất ngờ.",
    ticketPrice: 80000,
  },
  {
    id: 8,
    title: "Jujutsu Kaisen 0",
    titleVI: "Chú Thuật Hồi Chiến 0",
    genres: "Hành động",
    duration: 105,
    releaseDate: "05/05/2024",
    status: 2,
    posterUrl: "../image/jujutsu-kaisen-0-poster.webp",
    description:
      "Câu chuyện về Okkotsu Yuta và hành trình đối mặt với lời nguyền mạnh mẽ.",
    ticketPrice: 90000,
  },
  {
    id: 9,
    title: "Demon Slayer: Infinity Castle",
    titleVI: "Thanh Gươm Diệt Quỷ – Lâu Đài Vô Cực",
    genres: "Hành động",
    duration: 120,
    releaseDate: "15/05/2024",
    status: 2,
    posterUrl: "../image/demon-slayer-infinity-castle.jpg",
    description:
      "Tanjiro và các Trụ Cột đối đầu Muzan trong trận chiến tại lâu đài vô cực.",
    ticketPrice: 95000,
  },
  {
    id: 10,
    title: "A Silent Voice",
    titleVI: "Dáng hình thanh âm",
    genres: "Tâm lý",
    duration: 129,
    releaseDate: "22/05/2024",
    status: 0,
    posterUrl: "../image/a-silent-voice.webp",
    description:
      "Câu chuyện cảm động về tình bạn, sự tha thứ và hành trình chữa lành.",
    ticketPrice: 80000,
  },
  {
    id: 11,
    title: "Steins;Gate: Load Region of Déjà Vu",
    titleVI: "Steins;Gate: Load Region of Déjà Vu",
    genres: "Khoa học viễn tưởng",
    duration: 90,
    releaseDate: "01/06/2024",
    status: 2,
    posterUrl: "../image/steins-gate-movie.jpg",
    description:
      "Makise Kurisu và Okabe Rintarou đối mặt với những biến cố thời gian bất ngờ.",
    ticketPrice: 85000,
  },
  {
    id: 12,
    title: "Your Name",
    titleVI: "Tên Cậu Là Gì?",
    genres: "Tình cảm",
    duration: 106,
    releaseDate: "10/06/2024",
    status: 0,
    posterUrl: "../image/your-name.webp",
    description:
      "Hai thiếu niên hoán đổi thân xác và tìm cách gặp nhau giữa định mệnh.",
    ticketPrice: 80000,
  },
  {
    id: 13,
    title: "Avengers: Endgame",
    titleVI: "Avengers: Hồi Kết",
    genres: "Hành động",
    duration: 181,
    releaseDate: "26/04/2019",
    status: 0,
    posterUrl: "../image/avengers-endgame.jpg",
    description: "Các siêu anh hùng hợp sức chống lại Thanos để cứu vũ trụ.",
    ticketPrice: 100000,
  },
  {
    id: 14,
    title: "Inception",
    titleVI: "Kẻ Đánh Cắp Giấc Mơ",
    genres: "Khoa học viễn tưởng",
    duration: 148,
    releaseDate: "16/07/2010",
    status: 0,
    posterUrl: "../image/inception.jpg",
    description:
      "Một nhóm chuyên gia xâm nhập giấc mơ để đánh cắp và cấy ghép ý tưởng.",
    ticketPrice: 90000,
  },
  {
    id: 15,
    title: "Titanic",
    titleVI: "Titanic",
    genres: "Tình cảm",
    duration: 195,
    releaseDate: "19/12/1997",
    status: 0,
    posterUrl: "../image/titanic.jpg",
    description: "Chuyện tình bi thương trên con tàu Titanic huyền thoại.",
    ticketPrice: 85000,
  },
  {
    id: 16,
    title: "The Dark Knight",
    titleVI: "Kỵ Sĩ Bóng Đêm",
    genres: "Tội phạm",
    duration: 152,
    releaseDate: "18/07/2008",
    status: 0,
    posterUrl: "../image/dark-knight.webp",
    description: "Batman đối đầu Joker trong cuộc chiến bảo vệ Gotham.",
    ticketPrice: 90000,
  },
  {
    id: 17,
    title: "Interstellar",
    titleVI: "Hố Đen Vũ Trụ",
    genres: "Khoa học viễn tưởng",
    duration: 169,
    releaseDate: "07/11/2014",
    status: 0,
    posterUrl: "../image/interstellar.jpg",
    description:
      "Một nhóm phi hành gia vượt qua hố đen để tìm hành tinh mới cho nhân loại.",
    ticketPrice: 95000,
  },
  {
    id: 18,
    title: "Parasite",
    titleVI: "Ký Sinh Trùng",
    genres: "Tâm lý",
    duration: 132,
    releaseDate: "30/05/2019",
    status: 0,
    posterUrl: "../image/parasite.webp",
    description:
      "Gia đình nghèo tìm cách chen chân vào nhà giàu, dẫn đến bi kịch.",
    ticketPrice: 85000,
  },
  {
    id: 19,
    title: "Frozen",
    titleVI: "Nữ Hoàng Băng Giá",
    genres: "Phiêu lưu",
    duration: 102,
    releaseDate: "27/11/2013",
    status: 0,
    posterUrl: "../image/frozen.webp",
    description:
      "Câu chuyện về Elsa và Anna trong hành trình tìm lại tình yêu và sức mạnh.",
    ticketPrice: 80000,
  },
  {
    id: 20,
    title: "The Matrix",
    titleVI: "Ma Trận",
    genres: "Khoa học viễn tưởng",
    duration: 136,
    releaseDate: "31/03/1999",
    status: 0,
    posterUrl: "../image/matrix.jpg",
    description:
      "Neo khám phá sự thật về thế giới ảo và trở thành người được chọn.",
    ticketPrice: 90000,
  },
  {
    id: 21,
    title: "Grave of the Fireflies",
    titleVI: "Mộ Đom Đóm",
    genres: "Chiến tranh",
    duration: 89,
    releaseDate: "16/04/1988",
    status: 0,
    posterUrl: "../image/grave-of-the-fireflies.webp",
    description:
      "Câu chuyện cảm động về hai anh em Seita và Setsuko trong bối cảnh chiến tranh tàn khốc.",
    ticketPrice: 80000,
  },
];
localStorage.setItem("movies", JSON.stringify(movies));











let tickets = [
  {
    id: 1001,
    ticketCode: "VE-1001",
    customerName: "Nguyễn Văn A",
    customerPhone: "0987654321",
    movieId: 1,
    movieTitle: "Dune: Hành Tinh Cát - Phần 2",
    showDate: "2026-03-15",
    showTime: "10:00",
    seats: ["F12", "F13"],
    seatCount: 2,
    pricePerSeat: 90000,
    totalAmount: 180000,
    paymentMethod: 0, // 0: Tiền mặt, 1: Chuyển khoản, 2: Thẻ ngân hàng, 3: Ví điện tử, 4: Khác
    paymentStatus: true,
    createdAt: "2026-03-10T14:30:00Z",
    note: "Khách yêu cầu ghế gần lối đi",
    statusDisplay: "Đã Thanh Toán"
  },
  {
    id: 1002,
    ticketCode: "VE-1002",
    customerName: "Trần Thị B",
    customerPhone: "0912654321",
    movieId: 4,
    movieTitle: "Mai",
    showDate: "2026-03-16",
    showTime: "13:30",
    seats: ["G5"],
    seatCount: 1,
    pricePerSeat: 90000,
    totalAmount: 90000,
    paymentMethod: 1,
    paymentStatus: false,
    createdAt: "2026-03-11T09:15:00Z",
    note: "",
    statusDisplay: "Chờ xử lý"
  },
  {
    id: 1003,
    ticketCode: "VE-1003",
    customerName: "Lê Văn C",
    customerPhone: "090654321",
    movieId: 2,
    movieTitle: "Kung Fu Panda 4",
    showDate: "2026-03-17",
    showTime: "19:00",
    seats: ["H10", "H11", "H12"],
    seatCount: 3,
    pricePerSeat: 90000,
    totalAmount: 270000,
    paymentMethod: 2,
    paymentStatus: true,
    createdAt: "2026-03-12T16:45:00Z",
    note: "Combo bắp nước tặng kèm",
    statusDisplay: "Đã Thanh Toán"
  },
  {
    id: 1004,
    ticketCode: "VE-1004",
    customerName: "Phạm Minh D",
    customerPhone: "098654321",
    movieId: 5,
    movieTitle: "Exhuma: Quật Mộ Trùng Ma",
    showDate: "2026-03-14",
    showTime: "21:45",
    seats: ["E8"],
    seatCount: 1,
    pricePerSeat: 90000,
    totalAmount: 90000,
    paymentMethod: 0,
    paymentStatus: false,
    createdAt: "2026-03-13T11:20:00Z",
    note: "Khách huỷ do bận đột xuất",
    statusDisplay: "Đã huỷ"
  },
  {
    id: 1005,
    ticketCode: "VE-1005",
    customerName: "Hoàng Yến E",
    customerPhone: "0977654321",
    movieId: 3,
    movieTitle: "Godzilla x Kong: Đế Chế Mới",
    showDate: "2026-03-18",
    showTime: "09:15",
    seats: ["D4", "D5"],
    seatCount: 2,
    pricePerSeat: 90000,
    totalAmount: 180000,
    paymentMethod: 1,
    paymentStatus: false,
    createdAt: "2026-03-02T08:50:00Z",
    note: "Chờ xác nhận thanh toán chuyển khoản",
    statusDisplay: "Chờ xử lý"
  }
];
localStorage.setItem("tickets", JSON.stringify(tickets));

let users = [
  {
    id: 1,
    fullName: "Admin Chính",
    email: "LQTuan@rikkei.edu.vn",
    password: "Admin123456",
    role: "admin",
    createdAt: "2026-03-03T12:26:21.617Z",
    isActive: true
  },
  {
    id: 2,
    fullName: "Nguyễn Văn A",
    email: "nguyenvana@example.com",
    password: "Matkhau123",
    role: "user",
    createdAt: "2026-03-03T12:26:21.617Z",
    isActive: true
  },
  {
    id: 3,
    fullName: "Trần Thị B",
    email: "tranthib@example.com",
    password: "12345678",
    role: "user",
    createdAt: "2026-03-03T12:26:21.617Z",
    isActive: false
  }
];

localStorage.setItem("users", JSON.stringify(users));